#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

# @public Create a standalone instance of mongod that is running as a single
# server and not as part of a replica set.
function configure_standalone_mode() {
  local conf=${1:-}
  local comm="db.system.users.count({'user':'admin'})"

  if [[ -z "${conf}" ]]; then
    log_fail "Couldn't read config file. Conf is not set, no such file or directory"
    exit 1
  fi

  wait_for_mongo_up &>/dev/null

  if [[ "$($MONGOADMIN --quiet --eval "${comm}")" =~ "1" ]]; then
    mongo_reset_admin
  else
    mongo_create_admin
  fi

  if [[ -v CREATE_USER ]]; then
    comm="db.system.users.count({'user':'${MONGODB_USER:-}', 'db':'${MONGODB_DATABASE:-}'})"

    if [[ "$($MONGOADMIN --quiet --eval "${comm}")" =~ "1" ]]; then
      mongo_reset_user
    else
      mongo_create_user
    fi
  fi
}
readonly -f configure_standalone_mode
