#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

source ${CONTAINER_SCRIPTS_PATH:-}/db/common.sh

# @public  Checks environmental variables for mongos
#
function check_mongos_env_vars() {
    [[ -v CONFIG_REPLSET_NAME && -v CONFIG_REPLSET_SERVER ]] || usage "CONFIG_REPLSET_NAME and CONFIG_REPLSET_SERVER have to be set"
    [[ -v REPLSET_NAMES && -v REPLSET_SERVERS ]] || usage "REPLSET_NAMES and REPLSET_SERVERS have to be set"
}
readonly -f check_repl_env_vars


function configure_mongos() {

}
readonly -f configure_mongos
